title: I2 Grimoire
description: The I2 textbook on Artificial Intelligence
theme: just-the-docs
latex: mathjax

url: https://grimoire.uw-i2.org

aux_links:
  I2 Website: https://uw-i2.org
  Intro Course: https://course.uw-i2.org
  
search_enabled: false
