name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  LaTeX:
    permissions:
      contents: write
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: wtfjoke/setup-tectonic@v3
    
    - name: Run Tectonic
      run: tectonic main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf

    - name: Update PDF branch
      run: |
        # Move the PDF to a temporary location
        mv main.pdf /tmp
        
        # Configure git credentials
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'

        git fetch --all
        
        # Check if the PDF branch already exists
        ret_val=$( git ls-remote --heads origin refs/heads/PDF | wc -l )
        if [ $ret_val -eq 1 ]; then
          # Switch to the existing branch
          git switch PDF
        else
          # Create a new orphan branch
          git checkout --orphan PDF
          # Remove all files from the new orphan branch
          git rm -rf .
        fi
        
        cp /tmp/main.pdf 'I2 Grimore.pdf'
        
        # Add and commit changes
        git add 'I2 Grimore.pdf'
        git commit -m "Update PDF"
        
        # Push changes to the origin
        git push -u origin PDF
