name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job:
    permissions:
      contents: write
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf

    - name: Remove all files except PDF file
      run: find . ! -name 'main.pdf' -type f -delete

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Update PDF
        branch: pdf
    
