name: Compile Latex

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Comile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
        root_file: main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf
    
