name: Compile LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  LaTeX:
    permissions:
      contents: write
  
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main

    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      run: latexmk -pdf main.tex

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: main.pdf

    - name: Update PDF branch
      run: |
        cp main.pdf /tmp
        git checkout --orphan pdf && rm -rf . || git switch pdf
        mv /tmp/main.pdf .
        git push -u origin pdf
    
